'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRtl: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    about: 'About',
    portfolio: 'Portfolio',
    takeTest: 'Take Test',
    startAssessment: 'Start Assessment',
    learnMore: 'Learn More',
    heroHeadlineEn: 'Where success becomes a habit',
    heroSubheadlineEn: 'Empowering language learners in Egypt with ground-breaking teaching methods that unlock your full potential.',
    aboutHeadline: 'Language learning,<br>reimagined',
    aboutBody: 'Linguaplanet was born from a simple belief: every Egyptian deserves access to world-class English education. We blend ground-breaking pedagogy with genuine care for our students\' futures.',
    excellentServices: 'Excellent Services',
    excellentServicesDesc: 'We provide excellent language services at affordable prices.',
    affordablePricing: 'Affordable Pricing',
    affordablePricingDesc: 'We provide not only flexible price plans, but flexible modes of delivery as well.',
    groundBreakingApproaches: 'Ground-breaking Approaches',
    groundBreakingApproachesDesc: 'We use ground-breaking, top-notch approaches in language teaching.',
    ourValues: 'Our values',
    valuesHeadline: 'What drives us forward',
    quality: 'Quality',
    qualityValue: 'We strive to provide excellence.',
    flexibility: 'Flexibility',
    flexibilityValue: 'We provide a variety of options and solutions.',
    socialResponsibility: 'Social Responsibility',
    socialResponsibilityValue: 'We believe in giving back to the community.',
    whyChooseUs: 'Why choose us:',
    whyLinguaPlanet: 'Why LinguaPlanet?',
    qualityTitle: 'Quality',
    qualityBullet1: 'Ground-breaking and top-notch approaches to teaching and learning.',
    qualityBullet2: 'Universal standards of assessment and testing.',
    qualityBullet3: 'Quick results.',
    flexibilityTitle: 'Flexibility',
    flexibilityBullet1: 'Flexibility in the methods of delivery (F2F/Online) (Our own premises / The Clients).',
    flexibilityBullet2: 'Dates/Timing/Scheduling.',
    pricingTitle: 'Pricing',
    pricingBullet1: 'Variety of plans to suit your needs.',
    pricingBullet2: 'Very competitive pricing plans.',
    pricingBullet3: 'Variety of payment options.',
    reportingTitle: 'Reporting and Follow up',
    reportingBullet1: 'Get a detailed account of each group/student\'s performance.',
    reportingBullet2: 'Immediate notification of student\'s punctuality.',
    reportingBullet3: 'Tracking student\'s progress.',
    guaranteesTitle: 'Guarantees',
    guaranteesBullet1: 'Extra support for weak students.',
    guaranteesBullet2: 'Free review classes for failing students.',
    guaranteesBullet3: 'Openness to feedback and readiness to change and adaptability.',
    facingChallenges: 'Facing Challenges?',
    challenges1: 'Many candidates have great potentials and they are one step away from getting approvals.',
    challenges2: 'Unfortunately, they are short of the English requirement.',
    challenges3: 'Even those who could get into other programmes were hindered by their poor language abilities.',
    safeHands: 'You\'re in Safe Hands',
    safeHandsDesc: 'In their journey of learning English, they often stumble either due to the lack of financial resources or falling victims to low-quality language-service providers.',
    safeHandsDesc2: 'Thanks to Linguaplanet, this dilemma has ceased to exist.',
    safeHandsDesc3: 'We provide excellent services with a fraction of the price.',
    institutionalGuarantee: 'INSTITUTIONAL GRADE GUARANTEE',
    tagline: 'Languages and Training Services Institute',
    roleRecruitment: 'Recruitment and Talent Acquisition Manager',
    // ... existing translations ...
    aboutUs: 'About Us',
    contact: 'Contact',
    allRights: 'All rights reserved.',
    standardsTitle: 'The Linguaplanet Standard',
    operationalExcellence: 'Operational Excellence',
    qualityAssurance: 'Quality Assurance',
    eliteAcademicRigor: 'Elite Academic Rigor',
    pricingDesc: 'Variety of plans to suit your needs at very competitive prices. Multiple flexible payment options available for all programs.',
    trackingTitle: 'Tracking',
    reportingFollowup: 'Reporting & Follow-up',
    trackingDesc: 'Detailed accounts of student performance, immediate notification of punctuality, and systematic tracking of progress.',
    guaranteesTitle: 'Guarantees',
    institutionalSupport: 'Institutional Support',
    guaranteesDesc: 'Extra support for weak students, free review classes, and absolute openness to feedback and adaptability.',
    sendMessage: 'Send us a message',
    yourName: 'YOUR NAME',
    emailAddress: 'EMAIL ADDRESS',
    message: 'MESSAGE',
    sending: 'SENDING...',
    messageSent: 'MESSAGE SENT!',
    tryAgain: 'TRY AGAIN',
    thankYouMessage: 'Thank you! We will get back to you shortly.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    returnHome: 'RETURN TO HOME',
    pillars: 'Foundational Pillars',
    valuesTitle: 'The Values We Stand By',
    excellence: 'Excellence',
    excellenceDesc: 'We strive for the highest quality in every educational program we deliver.',
    integrity: 'Integrity',
    integrityDesc: 'Honesty and transparency are at the core of our institutional relationships.',
    innovation: 'Innovation',
    innovationDesc: 'Constantly evolving our methods to meet the future of global communication.',
    worldClassAcademy: 'WORLD CLASS LANGUAGE ACADEMY',
    programs: 'Programs',
    team: 'Our Team',
    arabicInterface: 'ARABIC INTERFACE',
    englishInterface: 'ENGLISH INTERFACE',
    evaluationComplete: 'EVALUATION COMPLETE',
    predictedLevel: 'Your Predicted Level',
    foundationTrack: 'Foundations of English',
    professionalTrack: 'Professional Communication Pro',
    executiveTrack: 'Executive Leadership & Advanced Rhetoric',
    returnToPortal: 'RETURN TO PORTAL',
    secureResults: 'SECURE YOUR RESULTS',
    finalStep: 'Final Step',
    generateReport: 'GENERATE MASTERY REPORT',
    selectRange: 'Select range...',
    kids: 'Kids (6-12)',
    teens: 'Teens (13-17)',
    adults: 'Adults (18+)',
    finalAssessment: 'FINAL ASSESSMENT',
    writingEvaluation: 'Writing Evaluation',
    writingPrompt: 'Choose ONE of the following topics (100-150 words):',
    writingTopic1: 'Your first job and daily routine.',
    writingTopic2: 'A country you visited on your last vacation.',
    submitAssessment: 'SUBMIT ASSESSMENT',
    phone: 'PHONE',
    part: 'PART',
    complete: 'COMPLETE',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    welcomeBack: 'Welcome Back',
    enterCredentials: 'ENTER YOUR CREDENTIALS',
    dontHaveAccount: "Don't have an account?",
    createProfile: 'CREATE A STUDENT PROFILE',
    authenticating: 'AUTHENTICATING...',
    joinAcademy: 'Join Linguaplanet',
    startJourney: 'START YOUR PROFESSIONAL JOURNEY',
    creatingProfile: 'CREATING PROFILE...',
    alreadyHaveAccount: 'Already have an account?',
    signInToDashboard: 'SIGN IN TO YOUR DASHBOARD',
    checkEmail: 'Check your email for the confirmation link!',
    password: 'PASSWORD',
    minCharacters: 'Minimum 6 characters',
    whatsappMessage: "Hello, I'm interested in your English and Soft Skills courses.",
    trustedBy: 'TRUSTED BY',
    companiesTrust: 'Companies that trust Linguaplanet',
    academicTracks: 'ACADEMIC TRACKS',
    ourPrograms: 'Our Programs',
    executiveLeadership: 'EXECUTIVE LEADERSHIP',
    mindsBehindSuccess: 'The Minds Behind Success',
    footerDesc: 'Where success becomes a habit. Empowering language learners in Egypt through institutional excellence since 2015.',
    corporate: 'CORPORATE',
    connectivity: 'CONNECTIVITY',
    aboutAcademy: 'About the Academy',
    leadershipTeam: 'Leadership Team',
    taxId: 'TAX ID',
    est2015: 'EST. 2015',
    cairoEgypt: 'Cairo, Egypt',
    generalEnglish: 'General English',
    businessCommunication: 'Business Communication',
    softSkillsMastery: 'Soft Skills Mastery',
    placementAssessment: 'Placement Assessment',
    program1Title: 'General English',
    program1Desc: 'Structured courses from A1 to C2 covering all core language skills with modern materials.',
    program2Title: 'Conversation Classes',
    program2Desc: 'Build real-world fluency fast with small groups and immersive speaking exercises.',
    program3Title: 'Business English',
    program3Desc: 'Master professional communication for emails, presentations, and global negotiations.',
    program4Title: 'IG / SAT Prep',
    program4Desc: 'Expert coaching and proven strategies to excel in international academic exams.',
    program5Title: 'IELTS / TOEFL',
    program5Desc: 'Achieve your target score with comprehensive prep, mock tests, and expert feedback.',
    program6Title: 'Soft Skills',
    program6Desc: 'Leadership, critical thinking, and public speaking — the skills that set you apart.',
    exploreTrack: 'EXPLORE TRACK',
    roleGM: 'General Manager',
    roleMarketing: 'Marketing Manager',
    aboutHeadline: 'Language <br/> learning, <br/> <span class="gold-text">reimagined</span>',
    aboutDescription: 'Linguaplanet was born from a simple belief: every Egyptian deserves access to world-class English education. We blend ground-breaking pedagogy with genuine care for our students\' futures.',
    pillar1Title: 'Excellent Services',
    pillar1Desc: 'We provide excellent language services at affordable prices.',
    pillar2Title: 'Affordable Pricing',
    pillar2Desc: 'We provide not only flexible price plans, but flexible modes of delivery as well.',
    pillar3Title: 'Ground-breaking Approaches',
    pillar3Desc: 'We use ground-breaking, top-notch approaches in language teaching.',
    ourValues: 'Our values',
    valuesSubtitle: 'What drives us forward',
    value1Title: 'Quality',
    value1Desc: 'We strive to provide excellence.',
    value2Title: 'Flexibility',
    value2Desc: 'We provide a variety of options and solutions.',
    value3Title: 'Social Responsibility',
    value3Desc: 'We believe in giving back to the community.',
    institutionalCore: 'INSTITUTIONAL CORE',
    visionMission: 'Our Vision & Mission',
    ourVision: 'OUR VISION',
    visionTitle: 'Achieve Effortlessly',
    visionDesc: 'Provide opportunities for language learners to unlock their full potentials and achieve their goals effortlessly.',
    ourMission: 'OUR MISSION',
    missionTitle: 'Lead and Support',
    missionDesc: 'Support and lead the English learning community in Egypt through innovation and excellence.',
    whyChooseUs: 'Why choose us:',
    whyLinguaPlanet: 'Why LinguaPlanet?',
    qualityTitle: 'Quality',
    qualityBullet1: 'Groundbreaking and top-notch approaches to teaching and learning.',
    qualityBullet2: 'Universal standards of assessment and testing.',
    qualityBullet3: 'Quick results.',
    flexibilityTitle: 'Flexibility',
    flexibilityBullet1: 'Flexibility in the methods of delivery (F2F/Online) (Our own premises / The Clients).',
    flexibilityBullet2: 'Dates/Timing/Scheduling.',
    pricingTitle: 'Pricing',
    pricingBullet1: 'Variety of plans to suit your needs.',
    pricingBullet2: 'Very competitive pricing plans.',
    pricingBullet3: 'Variety of payment options.',
    reportingTitle: 'Reporting and Follow up',
    reportingBullet1: 'Get a detailed account of each group/student\'s performance.',
    reportingBullet2: 'Immediate notification of student\'s punctuality.',
    reportingBullet3: 'Tracking student\'s progress.',
    guaranteesTitle: 'Guarantees',
    guaranteesBullet1: 'Extra support for weak students.',
    guaranteesBullet2: 'Free review classes for failing students.',
    guaranteesBullet3: 'Openness to feedback and readiness to change and adaptability.',
    facingChallenges: 'Facing Challenges?',
    challenges1: 'Many candidates have great potentials and they are one step away from getting approvals.',
    challenges2: 'Unfortunately, they are short of the English requirement.',
    challenges3: 'Even those who could get into other programmes were hindered by their poor language abilities.',
    safeHands: 'You\'re in Safe Hands',
    safeHandsDesc: 'In their journey of learning English, they often stumble either due to the lack of financial resources or falling victims to low-quality language-service providers.',
    safeHandsDesc2: 'Thanks to Linguaplanet, this dilemma has ceased to exist.',
    safeHandsDesc3: 'We provide excellent services with a fraction of the price.',
    institutionalGuarantee: 'INSTITUTIONAL GRADE GUARANTEE',
    learningEvolution: 'LEARNING EVOLUTION',
    professionalTrajectory: 'Your Professional Trajectory',
    milestoneA1: 'Beginner',
    milestoneA1Desc: 'Foundation skills',
    milestoneA2: 'Elementary',
    milestoneA2Desc: 'Social basics',
    milestoneB1: 'Intermediate',
    milestoneB1Desc: 'Workplace ready',
    milestoneB2: 'Upper-Int',
    milestoneB2Desc: 'Professional fluency',
    milestoneC1: 'Advanced',
    milestoneC1Desc: 'Academic excellence',
    milestoneC2: 'Mastery',
    milestoneC2Desc: 'Native-level executive',
    congrats: 'Congratulations {name}! You have demonstrated exceptional proficiency. Your score is {score}/{total}. Based on your performance, we recommend the following track:',
    welcomeStudent: 'Welcome, {name}',
    historyTitle: 'YOUR PROFESSIONAL ASSESSMENT HISTORY',
    noTests: 'No tests taken yet.',
    readyDiscover: 'Ready to discover your proficiency level?',
    startFirstTest: 'START YOUR FIRST TEST',
    loading: 'LOADING...',
    student: 'Student'
  },
  ar: {
    about: 'عن الأكاديمية',
    portfolio: 'الملف المهني',
    takeTest: 'خض الاختبار',
    startAssessment: 'ابدأ التقييم',
    learnMore: 'تعرف على المزيد',
    heroHeadlineEn: 'حيث يصبح النجاح عادة',
    heroSubheadlineEn: 'تمكين متعلمي اللغة في مصر بطرق تدريس مبتكرة تطلق العنان لإمكاناتك الكاملة.',
    aboutHeadline: 'تعلم اللغة،<br>برؤية جديدة',
    aboutBody: 'ولدت لنجوابلانيت من إيمان بسيط: كل مصري يستحق الوصول إلى تعليم لغة إنجليزية عالمي المستوى. نحن نمزج بين أساليب التدريس المبتكرة والرعاية الحقيقية لمستقبل طلابنا.',
    excellentServices: 'خدمات ممتازة',
    excellentServicesDesc: 'نحن نقدم خدمات لغوية ممتازة بأسعار مناسبة.',
    affordablePricing: 'أسعار مناسبة',
    affordablePricingDesc: 'نحن لا نوفر خطط أسعار مرنة فحسب، بل نوفر طرقاً مرنة لتقديم الخدمة أيضاً.',
    groundBreakingApproaches: 'أساليب مبتكرة',
    groundBreakingApproachesDesc: 'نحن نستخدم أساليب مبتكرة وعالية المستوى في تعليم اللغة.',
    ourValues: 'قيمنا',
    valuesHeadline: 'ما يدفعنا للأمام',
    quality: 'الجودة',
    qualityValue: 'نحن نسعى جاهدين لتحقيق التميز.',
    flexibility: 'المرونة',
    flexibilityValue: 'نحن نقدم مجموعة متنوعة من الخيارات والحلول.',
    socialResponsibility: 'المسؤولية الاجتماعية',
    socialResponsibilityValue: 'نحن نؤمن برد الجميل للمجتمع.',
    whyChooseUs: 'لماذا تختارنا:',
    whyLinguaPlanet: 'لماذا لنجوابلانيت؟',
    qualityTitle: 'الجودة',
    qualityBullet1: 'أساليب مبتكرة وعالية المستوى في التدريس والتعلم.',
    qualityBullet2: 'معايير عالمية للتقييم والاختبار.',
    qualityBullet3: 'نتائج سريعة.',
    flexibilityTitle: 'المرونة',
    flexibilityBullet1: 'مرونة في طرق تقديم الخدمة (حضورياً/أونلاين) (في مقرنا / لدى العميل).',
    flexibilityBullet2: 'التواريخ/المواعيد/الجدولة.',
    pricingTitle: 'التسعير',
    pricingBullet1: 'مجموعة متنوعة من الخطط لتناسب احتياجاتك.',
    pricingBullet2: 'خطط تسعير تنافسية للغاية.',
    pricingBullet3: 'مجموعة متنوعة من خيارات الدفع.',
    reportingTitle: 'التقارير والمتابعة',
    reportingBullet1: 'احصل على تقرير مفصل عن أداء كل مجموعة/طالب.',
    reportingBullet2: 'إخطار فوري بانضباط الطالب.',
    reportingBullet3: 'تتبع تقدم الطالب.',
    guaranteesTitle: 'الضمانات',
    guaranteesBullet1: 'دعم إضافي للطلاب الضعاف.',
    guaranteesBullet2: 'حصص مراجعة مجانية للطلاب الذين لم يوفقوا.',
    guaranteesBullet3: 'الانفتاح على الملاحظات والاستعداد للتغيير والتكيف.',
    facingChallenges: 'هل تواجه تحديات؟',
    challenges1: 'يمتلك العديد من المرشحين إمكانات كبيرة وهم على بعد خطوة واحدة من الحصول على الموافقات.',
    challenges2: 'للأسف، هم يفتقرون إلى متطلبات اللغة الإنجليزية.',
    challenges3: 'حتى أولئك الذين تمكنوا من الالتحاق ببرامج أخرى تعثروا بسبب قدراتهم اللغوية الضعيفة.',
    safeHands: 'أنت في أيدٍ أمينة',
    safeHandsDesc: 'في رحلتهم لتعلم اللغة الإنجليزية، غالباً ما يتعثرون إما بسبب نقص الموارد المالية أو الوقوع ضحايا لمزودي خدمات لغوية منخفضي الجودة.',
    safeHandsDesc2: 'بفضل لنجوابلانيت، لم تعد هذه المعضلة موجودة.',
    safeHandsDesc3: 'نحن نقدم خدمات ممتازة بجزء بسيط من السعر.',
    institutionalGuarantee: 'ضمان الدرجة المؤسسية',
    tagline: 'معهد اللغات وخدمات التدريب',
    roleRecruitment: 'مدير التوظيف واستقطاب المواهب',
    // ... existing translations ...
    aboutUs: 'من نحن',
    contact: 'اتصل بنا',
    allRights: 'جميع الحقوق محفوظة.',
    standardsTitle: 'معيار لنجوابلانيت',
    operationalExcellence: 'التميز التشغيلي',
    qualityAssurance: 'ضمان الجودة',
    eliteAcademicRigor: 'الصرامة الأكاديمية المتميزة',
    pricingDesc: 'مجموعة متنوعة من الخطط لتناسب احتياجاتك بأسعار تنافسية للغاية. خيارات دفع مرنة متعددة متاحة لجميع البرامج.',
    trackingTitle: 'المتابعة',
    reportingFollowup: 'التقارير والمتابعة',
    trackingDesc: 'تقارير مفصلة عن أداء الطلاب، إخطار فوري بالمواعيد، وتتبع منهجي للتقدم.',
    guaranteesTitle: 'الضمانات',
    institutionalSupport: 'الدعم المؤسسي',
    guaranteesDesc: 'دعم إضافي للطلاب الضعاف، حصص مراجعة مجانية، وانفتاح تام على الملاحظات والقدرة على التكيف.',
    sendMessage: 'أرسل لنا رسالة',
    yourName: 'اسمك',
    emailAddress: 'البريد الإلكتروني',
    message: 'الرسالة',
    sending: 'جاري الإرسال...',
    messageSent: 'تم إرسال الرسالة!',
    tryAgain: 'حاول مرة أخرى',
    thankYouMessage: 'شكراً لك! سنرد عليك قريباً.',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    returnHome: 'العودة للرئيسية',
    pillars: 'أركاننا الأساسية',
    valuesTitle: 'القيم التي نؤمن بها',
    excellence: 'التميز',
    excellenceDesc: 'نسعى لتحقيق أعلى مستويات الجودة في كل برنامج تعليمي نقدمه.',
    integrity: 'النزاهة',
    integrityDesc: 'الصدق والشفافية هما جوهر علاقاتنا المؤسسية.',
    innovation: 'الابتكار',
    innovationDesc: 'تطوير مستمر لأساليبنا لمواكبة مستقبل التواصل العالمي.',
    worldClassAcademy: 'أكاديمية لغات عالمية المستوى',
    programs: 'البرامج',
    team: 'فريقنا',
    arabicInterface: 'الواجهة العربية',
    englishInterface: 'الإجهة الإنجليزية',
    evaluationComplete: 'اكتمل التقييم',
    predictedLevel: 'مستوى كفاءتك التنبؤي',
    foundationTrack: 'أساسيات اللغة الإنجليزية',
    professionalTrack: 'اتصالات مهنية للمحترفين',
    executiveTrack: 'القيادة التنفيذية والبلاغة المتقدمة',
    returnToPortal: 'العودة للرئيسية',
    secureResults: 'احفظ نتائجك',
    finalStep: 'الخطوة الأخيرة',
    generateReport: 'إنشاء تقرير الإتقان',
    selectRange: 'اختر الفئة...',
    kids: 'الأطفال (6-12)',
    teens: 'الناشئين (13-17)',
    adults: 'الكبار (18+)',
    finalAssessment: 'التقييم النهائي',
    writingEvaluation: 'تقييم الكتابة',
    writingPrompt: 'اختر أحد المواضيع التالية (100-150 كلمة):',
    writingTopic1: 'وظيفتك الأولى وروتينك اليومي.',
    writingTopic2: 'بلد زرته في عطلتك الأخيرة.',
    submitAssessment: 'إرسال التقييم',
    phone: 'رقم الهاتف',
    part: 'الجزء',
    complete: 'مكتمل',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signOut: 'تسجيل الخروج',
    welcomeBack: 'مرحباً بعودتك',
    enterCredentials: 'أدخل بيانات الاعتماد الخاصة بك',
    dontHaveAccount: 'ليس لديك حساب؟',
    createProfile: 'إنشاء ملف تعريف طالب',
    authenticating: 'جاري التحقق...',
    joinAcademy: 'انضم إلى لنجوابلانيت',
    startJourney: 'ابدأ رحلتك المهنية',
    creatingProfile: 'جاري إنشاء ملف التعريف...',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    signInToDashboard: 'تسجيل الدخول إلى لوحة التحكم الخاصة بك',
    checkEmail: 'تحقق من بريدك الإلكتروني للحصول على رابط التأكيد!',
    password: 'كلمة المرور',
    minCharacters: '6 أحرف على الأقل',
    whatsappMessage: 'مرحباً، أنا مهتم بدورات اللغة الإنجليزية والمهارات الشخصية الخاصة بكم.',
    trustedBy: 'موثوق به من قبل',
    companiesTrust: 'شركات تثق في لنجوابلانيت',
    academicTracks: 'المسارات الأكاديمية',
    ourPrograms: 'برامجنا',
    executiveLeadership: 'القيادة التنفيذية',
    mindsBehindSuccess: 'العقول وراء النجاح',
    footerDesc: 'حيث يصبح النجاح عادة. تمكين متعلمي اللغة في مصر من خلال التميز المؤسسي منذ عام 2015.',
    corporate: 'المؤسسة',
    connectivity: 'التواصل',
    aboutAcademy: 'عن الأكاديمية',
    leadershipTeam: 'فريق القيادة',
    taxId: 'البطاقة الضريبية',
    est2015: 'تأسست عام 2015',
    cairoEgypt: 'القاهرة، مصر',
    generalEnglish: 'اللغة الإنجليزية العامة',
    businessCommunication: 'التواصل في مجال الأعمال',
    softSkillsMastery: 'إتقان المهارات الشخصية',
    placementAssessment: 'تقييم تحديد المستوى',
    program1Title: 'اللغة الإنجليزية العامة',
    program1Desc: 'دورات منظمة من A1 إلى C2 تغطي جميع المهارات اللغوية الأساسية بمواد حديثة.',
    program2Title: 'حصص المحادثة',
    program2Desc: 'ابنِ طلاقة حقيقية بسرعة مع مجموعات صغيرة وتمارين محادثة غامرة.',
    program3Title: 'الإنجليزية للأعمال',
    program3Desc: 'أتقن التواصل المهني لرسائل البريد الإلكتروني والعروض التقديمية والمفاوضات العالمية.',
    program4Title: 'التحضير لـ IG / SAT',
    program4Desc: 'تدريب خبير واستراتيجيات مثبتة للتميز في الامتحانات الأكاديمية الدولية.',
    program5Title: 'IELTS / TOEFL',
    program5Desc: 'حقق درجتك المستهدفة من خلال التحضير الشامل والاختبارات التجريبية والتعليقات الخبيرة.',
    program6Title: 'المهارات الشخصية',
    program6Desc: 'القيادة والتفكير النقدي والخطابة - المهارات التي تميزك.',
    exploreTrack: 'استكشف المسار',
    roleGM: 'المدير العام',
    roleMarketing: 'مدير التسويق',
    aboutHeadline: 'تعلم اللغة <br/> برؤية <br/> <span class="gold-text">جديدة</span>',
    aboutDescription: 'ولدت لنجوابلانيت من إيمان بسيط: كل مصري يستحق الوصول إلى تعليم لغة إنجليزية عالمي المستوى. نحن نمزج بين أساليب التدريس المبتكرة والرعاية الحقيقية لمستقبل طلابنا.',
    pillar1Title: 'خدمات ممتازة',
    pillar1Desc: 'نحن نقدم خدمات لغوية ممتازة بأسعار مناسبة.',
    pillar2Title: 'أسعار مناسبة',
    pillar2Desc: 'نحن لا نوفر خطط أسعار مرنة فحسب، بل نوفر طرقاً مرنة لتقديم الخدمة أيضاً.',
    pillar3Title: 'أساليب مبتكرة',
    pillar3Desc: 'نحن نستخدم أساليب مبتكرة وعالية المستوى في تعليم اللغة.',
    ourValues: 'قيمنا',
    valuesSubtitle: 'ما يدفعنا للأمام',
    value1Title: 'الجودة',
    value1Desc: 'نحن نسعى جاهدين لتحقيق التميز.',
    value2Title: 'المرونة',
    value2Desc: 'نحن نقدم مجموعة متنوعة من الخيارات والحلول.',
    value3Title: 'المسؤولية الاجتماعية',
    value3Desc: 'نحن نؤمن برد الجميل للمجتمع.',
    visionMission: 'رؤيتنا ورسالتنا',
    ourVision: 'رؤيتنا',
    visionTitle: 'حقق أهدافك بسهولة',
    visionDesc: 'توفير الفرص لمتعلمي اللغة لإطلاق كامل إمكاناتهم وتحقيق أهدافهم بسهولة.',
    ourMission: 'رسالتنا',
    missionTitle: 'القيادة والدعم',
    missionDesc: 'دعم وقيادة مجتمع تعلم اللغة الإنجليزية في مصر من خلال الابتكار والتميز.',
    whyChooseUs: 'لماذا تختارنا:',
    whyLinguaPlanet: 'لماذا لنجوابلانيت؟',
    qualityTitle: 'الجودة',
    qualityBullet1: 'أساليب مبتكرة وعالية المستوى في التدريس والتعلم.',
    qualityBullet2: 'معايير عالمية للتقييم والاختبار.',
    qualityBullet3: 'نتائج سريعة.',
    flexibilityTitle: 'المرونة',
    flexibilityBullet1: 'مرونة في طرق تقديم الخدمة (حضورياً/أونلاين) (في مقرنا / لدى العميل).',
    flexibilityBullet2: 'التواريخ/المواعيد/الجدولة.',
    pricingTitle: 'التسعير',
    pricingBullet1: 'مجموعة متنوعة من الخطط لتناسب احتياجاتك.',
    pricingBullet2: 'خطط تسعير تنافسية للغاية.',
    pricingBullet3: 'مجموعة متنوعة من خيارات الدفع.',
    reportingTitle: 'التقارير والمتابعة',
    reportingBullet1: 'احصل على تقرير مفصل عن أداء كل مجموعة/طالب.',
    reportingBullet2: 'إخطار فوري بانضباط الطالب.',
    reportingBullet3: 'تتبع تقدم الطالب.',
    guaranteesTitle: 'الضمانات',
    guaranteesBullet1: 'دعم إضافي للطلاب الضعاف.',
    guaranteesBullet2: 'حصص مراجعة مجانية للطلاب الذين لم يوفقوا.',
    guaranteesBullet3: 'الانفتاح على الملاحظات والاستعداد للتغيير والتكيف.',
    facingChallenges: 'هل تواجه تحديات؟',
    challenges1: 'يمتلك العديد من المرشحين إمكانات كبيرة وهم على بعد خطوة واحدة من الحصول على الموافقات.',
    challenges2: 'للأسف، هم يفتقرون إلى متطلبات اللغة الإنجليزية.',
    challenges3: 'حتى أولئك الذين تمكنوا من الالتحاق ببرامج أخرى تعثروا بسبب قدراتهم اللغوية الضعيفة.',
    safeHands: 'أنت في أيدٍ أمينة',
    safeHandsDesc: 'في رحلتهم لتعلم اللغة الإنجليزية، غالباً ما يتعثرون إما بسبب نقص الموارد المالية أو الوقوع ضحايا لمزودي خدمات لغوية منخفضي الجودة.',
    safeHandsDesc2: 'بفضل لنجوابلانيت، لم تعد هذه المعضلة موجودة.',
    safeHandsDesc3: 'نحن نقدم خدمات ممتازة بجزء بسيط من السعر.',
    institutionalGuarantee: 'ضمان الدرجة المؤسسية',
    learningEvolution: 'تطور التعلم',
    professionalTrajectory: 'مسارك المهني',
    milestoneA1: 'مبتدئ',
    milestoneA1Desc: 'مهارات التأسيس',
    milestoneA2: 'أولي',
    milestoneA2Desc: 'أساسيات التواصل',
    milestoneB1: 'متوسط',
    milestoneB1Desc: 'جاهز للعمل',
    milestoneB2: 'فوق المتوسط',
    milestoneB2Desc: 'طلاقة مهنية',
    milestoneC1: 'متقدم',
    milestoneC1Desc: 'تميز أكاديمي',
    milestoneC2: 'إتقان',
    milestoneC2Desc: 'مستوى تنفيذي عالمي',
    congrats: 'تهانينا {name}! لقد أظهرت كفاءة استثنائية. درجتك هي {score} من {total}. بناءً على أدائك، نوصي بالمسار التالي:',
    welcomeStudent: 'مرحباً، {name}',
    historyTitle: 'سجل التقييم المهني الخاص بك',
    noTests: 'لم يتم إجراء أي اختبارات بعد.',
    readyDiscover: 'هل أنت مستعد لاكتشاف مستوى كفاءتك؟',
    startFirstTest: 'ابدأ اختبارك الأول',
    loading: 'جاري التحميل...',
    student: 'طالب'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang) {
      setTimeout(() => setLanguage(savedLang), 0);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRtl, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
